name: ubuntu-build

on:
  push:
    branches: [ "*master*" ]
  pull_request:
    branches: [ "*master*" ]

concurrency:
  group: "core-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    name: ubuntu-24.04-g++

    steps:
    - name: Checkout YggdrasilCore
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/var/ccache
        key: ccache:ubuntu-24.04:gcc:${{ github.ref }}:${{ github.sha }}
        restore-keys: |
          ccache:ubuntu-24.04:gcc:${{ github.ref }}
          ccache:ubuntu-24.04:gcc
          ccache:ubuntu-24.04

    - name: Install Requirements
      run: sudo apt-get update && sudo apt-get install ccache git cmake make gcc g++ clang libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mysql-server libboost-all-dev

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_FLAGS="-DMOD_SHADOWS"
        -DCMAKE_CXX_FLAGS="-DMOD_SHADOWS"
        -DCMAKE_C_COMPILER_LAUNCHER="ccache"
        -DCMAKE_CXX_COMPILER_LAUNCHER="ccache"
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --parallel $(nproc)
